name: Running a script
on:
  push:
   branches: main
jobs:
 uses:
  runs-on: ubuntu-latest
  steps:
   - name: run scripts
     run: |
        echo "Current date and time:"
        date
        echo "List of files in the current directory:"
        ls -l
